# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(853, 731)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.left_col = QtWidgets.QVBoxLayout()
        self.left_col.setObjectName("left_col")
        self.new_note = QtWidgets.QPushButton(self.centralwidget)
        self.new_note.setStyleSheet("\n"
"border: 2px solid teal;\n"
"border-radius: 10px;\n"
"\n"
"padding: 10px;\n"
"margin-bottom: 10px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/circle-plus.svg"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.new_note.setIcon(icon)
        self.new_note.setObjectName("new_note")
        self.left_col.addWidget(self.new_note)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.search_line = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_line.sizePolicy().hasHeightForWidth())
        self.search_line.setSizePolicy(sizePolicy)
        self.search_line.setMinimumSize(QtCore.QSize(150, 0))
        self.search_line.setMaximumSize(QtCore.QSize(200, 16777215))
        self.search_line.setObjectName("search_line")
        self.horizontalLayout_3.addWidget(self.search_line)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(120, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(200, 16777212))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/search (1).svg"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.pushButton.setIcon(icon1)
        self.pushButton.setAutoRepeatInterval(101)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.left_col.addLayout(self.horizontalLayout_3)
        self.notes_list = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notes_list.sizePolicy().hasHeightForWidth())
        self.notes_list.setSizePolicy(sizePolicy)
        self.notes_list.setMinimumSize(QtCore.QSize(256, 0))
        self.notes_list.setObjectName("notes_list")
        self.left_col.addWidget(self.notes_list)
        self.horizontalLayout_2.addLayout(self.left_col)
        self.right_col = QtWidgets.QVBoxLayout()
        self.right_col.setObjectName("right_col")
        self.note_title = QtWidgets.QLineEdit(self.centralwidget)
        self.note_title.setObjectName("note_title")
        self.right_col.addWidget(self.note_title)
        self.note_text = QtWidgets.QTextEdit(self.centralwidget)
        self.note_text.setObjectName("note_text")
        self.right_col.addWidget(self.note_text)
        self.save_btn = QtWidgets.QPushButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/device-floppy.svg"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.save_btn.setIcon(icon2)
        self.save_btn.setObjectName("save_btn")
        self.right_col.addWidget(self.save_btn)
        self.delete_btn = QtWidgets.QPushButton(self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/trash-x.svg"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.delete_btn.setIcon(icon3)
        self.delete_btn.setObjectName("delete_btn")
        self.right_col.addWidget(self.delete_btn)
        self.horizontalLayout_2.addLayout(self.right_col)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 853, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.new_note.setText(_translate("MainWindow", "Нова замітка"))
        self.search_line.setPlaceholderText(_translate("MainWindow", "Пошук замітки"))
        self.pushButton.setText(_translate("MainWindow", "Шукати"))
        self.note_title.setPlaceholderText(_translate("MainWindow", "Назва замітки"))
        self.note_text.setPlaceholderText(_translate("MainWindow", "Текст замітки"))
        self.save_btn.setText(_translate("MainWindow", "Зберегти"))
        self.delete_btn.setText(_translate("MainWindow", "Видалити"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
